export { addData } from './addData'
export { addGetMethod } from './addGetMethod'
export { addPostMethod } from './addPostMethod'
export { addInternalHeader } from './addInternalHeader'
export { addDeleteMethod } from './addDeleteMethod'
