name: Deploy Swagger

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm i

      - name: Build shared
        run: |
          nx build shared

      - name: Build auth-service
        run: |
          nx build auth-service

      - name: Build Swagger
        run: |
          npm run generate:swagger --workspace=apps/auth-service

      - name: Create dist directory structure
        run: |
          mkdir -p .dist/auth

      - name: Copy swagger.json to dist
        run: |
          cp apps/auth-service/dist/swagger.json .dist/auth/swagger.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.dist
